% Get type name (as string) from type id.
function ty = tyname(id)
   tynames = { ...
      'int8', ...
      'uint8', ...
      'int16', ...
      'uint16', ...
      'int32', ...
      'uint32', ...
      'float32', ...
      'float64' ...
   };
   if ((1 <= id) && (id <= numel(tynames)))
      ty = tynames{id};
   else
      error('type not supported');
   end
end
